version: 2
jobs:
  test:
    docker:
      - image: microsoft/powershell:ubuntu-16.04
    steps:
      - checkout
      - run:
          name: Test module
          command: pwsh -File ./.circleci/scripts/test-module.ps1
      - store_test_results:
          path: /output/test-results
      - store_artifacts:
          path: /output/test-results
          destination: test-results
      - persist_to_workspace:
          root: /output/workspace/
          paths:
            - ./*

  pre-release-checks:
    docker:
      - image: microsoft/powershell:ubuntu-16.04
        command: pwsh
    steps:
      - checkout
      - run:
          name: Pre-release checks
          command: pwsh -File ./.circleci/scripts/pre-release-checks.ps1

  publish-powershell-gallery:
    docker:
      - image: microsoft/powershell:ubuntu-16.04
        command: pwsh
    steps:
      - checkout
      - run:
          name: Install .Net Core SDK
          command: apt-get update && apt-get install -y dotnet-sdk-2.1.4
      - run:
          name: Publish module to PowerShell Gallery
          command: |
            cd ..
            mv project qlik-cli
            cd qlik-cli
            pwsh -Command 'Publish-Module `
              -Path ./ `
              -NuGetApiKey $env:PSG_API_KEY `
              -Tags Qlik, Sense, Windows `
              -Verbose'

  publish-github-release:
    docker:
      - image: cibuilds/github:latest
    steps:
      - attach_workspace:
          at: /output/workspace
      - run:
          name: Publish release on GitHub
          command: |
            VERSION=$(cat /output/workspace/version)
            ghr -t ${GITHUB_TOKEN} \
                -u ${CIRCLE_PROJECT_USERNAME} \
                -r ${CIRCLE_PROJECT_REPONAME} \
                -c ${CIRCLE_SHA1} \
                ${VERSION} \
                /output/workspace/Qlik-Cli.psm1

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-pages
      - pre-release-checks:
          requires:
            - test
          filters:
            branches:
              only: testing
      - publish-powershell-gallery:
          requires:
            - test
          filters:
            branches:
              only: master
      - publish-github-release:
          requires:
            - test
          filters:
            branches:
              only: master
