version: 2
jobs:
  build:
    docker:
      - image: microsoft/powershell:latest
        command: pwsh
    steps:
      - checkout
      - run:
          name: Check version has been incremented in manifest
          command: pwsh -Command 'if ((Test-ModuleManifest -Path ./Qlik-Cli.psd1).Version -le (Find-Module -Name Qlik-Cli).Version) {Write-Error "Version must be newer"}'
      - run:
          name: Check that the modules can be imported
          command: pwsh -Command 'Import-Module ./Qlik-Cli.psd1'
      - run:
          name: Check that the loaded module version matches the manifest
          command: pwsh -Command 'if (Import-Module ./Qlik-Cli.psd1; (Test-ModuleManifest -Path ./Qlik-Cli.psd1).Version -ne (Get-Module -Name Qlik-Cli).Version) {Write-Error "Version does not match"}'
