version: 2
jobs:
  test:
    docker:
      - image: microsoft/powershell:latest
    steps:
      - checkout
      - run:
          name: Install Pester module
          command: pwsh -Command 'Install-Module Pester -Force'
      - run:
          name: Check that the modules can be imported
          command: pwsh -Command 'Import-Module ./Qlik-Cli.psd1'
      - run:
          name: Check that the loaded module version matches the manifest
          command: |
            pwsh -Command '
              Import-Module ./Qlik-Cli.psd1
              if ((Test-ModuleManifest -Path ./Qlik-Cli.psd1).Version -ne (Get-Module -Name Qlik-Cli).Version) {
                Write-Error "Version does not match"
              }'
      - run:
          name: Run Pester tests
          command: |
            pwsh -Command '
              New-Item `
                -ItemType Directory `
                -Path /output/test-results/pester

              Invoke-Pester `
                -EnableExit `
                -OutputFile /output/test-results/pester/results.xml'
      - store_test_results:
          path: /output/test-results
      - store_artifacts:
          path: /output/test-results
          destination: test-results
      - run:
          name: Concatenate scripts into single module file
          command: |
            pwsh -Command '
              $mod = Import-LocalizedData -FileName Qlik-Cli.psd1
              $mod.NestedModules + $mod.RootModule |
                %{Get-Content -raw $_} |
                Out-File ./Qlik-Cli-Merged.psm1 -Encoding utf8
            '
      - run:
          name: Test merged module exports all commands
          command: |
            pwsh -Command '
              Import-Module ./Qlik-Cli.psd1 -Force
              $SplitCount = (Get-Command -Module Qlik-Cli).Count
              Import-Module ./Qlik-Cli-Merged.psm1 -Force
              $MergedCount = (Get-Command -Module Qlik-Cli-Merged).Count
              if ($SplitCount -ne $MergedCount) {
                Write-Error ("Merged module contains wrong number of commands," `
                           + " has $MergedCount and should have $SplitCount")
              }

              New-Item `
                -ItemType Directory `
                -Path /output/workspace

              Copy-Item ./Qlik-Cli-Merged.psm1 /output/workspace/Qlik-Cli.psm1
              (Get-Module Qlik-Cli).Version.ToString() |
                Out-File /output/workspace/version -Encoding utf8'
      - persist_to_workspace:
          root: /output/workspace/
          paths:
            - ./*

  publish-powershell-gallery:
    docker:
      - image: microsoft/powershell:latest
        command: pwsh
    steps:
      - checkout
      - run:
          name: Check version has been incremented in manifest
          command: |
            pwsh -Command '
              if ((Test-ModuleManifest -Path ./Qlik-Cli.psd1).Version -le (Find-Module -Name Qlik-Cli).Version) {
                Write-Error "Version must be newer"
              }'
      - run:
          name: Install .Net Core SDK
          command: apt-get update && apt-get install -y dotnet-sdk-2.1.4
      - run:
          name: Publish module to PowerShell Gallery
          command: |
            cd ..
            mv project qlik-cli
            cd qlik-cli
            pwsh -Command 'Publish-Module -Path ./ -NuGetApiKey $env:PSG_API_KEY -Verbose'
      - run:
          name: Check published version matches module version
          command: |
            pwsh -Command '
              if ((Test-ModuleManifest -Path ./Qlik-Cli.psd1).Version -ne (Find-Module -Name Qlik-Cli).Version) {
                Write-Error "Published version does not match"
              }'

  publish-github-release:
    docker:
      - image: cibuilds/github:latest
    steps:
      - attach_workspace:
          at: /output/workspace
      - run:
          name: Publish release on GitHub
          command: |
            VERSION=$(cat /output/workspace/version)
            ghr -t ${GITHUB_TOKEN} \
                -u ${CIRCLE_PROJECT_USERNAME} \
                -r ${CIRCLE_PROJECT_REPONAME} \
                -c ${CIRCLE_SHA1} \
                ${VERSION} \
                /output/workspace/Qlik-Cli.psm1

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - publish-powershell-gallery:
          requires:
            - test
          filters:
            branches:
              only: master
      - publish-github-release:
          requires:
            - test
          filters:
            branches:
              only: master
